import type { Metadata } from "next";

import { Roboto } from "next/font/google";

import "./globals.css";
import { SessionContextProvider } from "@/app/context/SessionContext";

import Aside from "./components/Aside";
const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});
// const inter = Inter({subsets: ["latin"], weight: "400"});

export const metadata: Metadata = {
  title: "Burgerli - sistema de gestionamiento",
  description: "Generated by appncy",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es">
      <SessionContextProvider>
        <body className={`${roboto.className} h-full bg-white antialiased`}>
          <Aside />
          {children}
        </body>
      </SessionContextProvider>
    </html>
  );
}
